export const darkGray = '#AAA'
export const gray = '#DFDFDF'
export const lightPurp = '#7C53C3'
export const purple = '#7A3EE8'
export const orange = '#F26f28'
export const red = '#990000'
export const textGray = '#666'
export const white = '#FFF'